### ISSUE TITLE
Subscribe example

### ISSUE THREAD

**Issue by demket** [vaphes/pocketbase#69]
Hi, I need subscribe example both httpx and python sdk, please.

**Comment by m29h** [comment]
Have you looked into this [integration test](https://github.com/vaphes/pocketbase/blob/4fb6458fbad32ac7029f68afc45c22a2f6b77243/tests/integration/test_record_event.py#L29-L54)

This shows how to register a subscription callback and also what happens if a record you have subscribed to triggers the callback.
