### ISSUE TITLE
[Help] How to get record data ... ?

### ISSUE THREAD

**Issue by Saad5400** [vaphes/pocketbase#83]
```python
record = pb.collection('abc').get_one(id)
record['xyz']  # error
record.xyz  # error
record.__getattribute__('xyz') # you guessed it, error
```

A little bit more examples on the readme would be nice

**Comment by m29h** [comment]
Please have a look at our integration tests

https://github.com/vaphes/pocketbase/blob/master/tests%2Fintegration%2Ftest_record.py#L92

This test does exactly what you seem to want.

`record.xyz` in your example should work perfectly fine in case the table `abc` has a field `xyz`

Not sure what your problem is...

**Comment by m29h** [comment]
Closed due to inactivity
