### ISSUE TITLE
httpx too old version

### ISSUE THREAD

**Issue by Glavnyuk** [vaphes/pocketbase#93]
need bump httpx version to  >=0.27.0

**Comment by jwang-paradise** [comment]
I'm having the same issue. This has to do with the poetry dependency spec, in 
[pyproject.toml#L42](https://github.com/vaphes/pocketbase/blob/e23a956b613ec15fb2a510df57e68e7bec1afbe0/pyproject.toml#L42):
```
[tool.poetry.dependencies]
httpx = "^0.24.1"
```
The `"^0.24.1"` specifier allows only >=0.24.1 and <0.25.0.  Ref: Caret requirements - [Dependency specification | Documentation | Poetry](https://python-poetry.org/docs/dependency-specification/#caret-requirements)

Changing it to `"^0.24"` will allow a wider range of version (>=0.24, <1.0), and should solve this issue.

**Comment by vaphes** [comment]
@Glavnyuk and @jwang-paradise
Man I really need coffee today, made a mess on comments and didn't reference this issue on the last PR. Can you check if the issue is solved with the last commit on master?

**Comment by jwang-paradise** [comment]
I built this patch and the requirement in the _built package_ has changed:
```diff
+ Requires-Dist: httpx (>=0,<1)
- Requires-Dist: httpx (>=0.24.1,<0.25.0)
```
Definitely allows newer versions of httpx.

But I'm sorry about the mistake in my last comment: the specifier `"^0.24"` actually compiled to (>=0,<1), not (>=0.24, <1.0).  If httpx versions <0.24 are incompatible, maybe [inequality requirements](https://python-poetry.org/docs/dependency-specification/#inequality-requirements) will have to used, i.e. `">=0.24, <1.0"`.

Otherwise it's perfectly ok. Works fine on my project now!
